In [3]:
import pandas as pd
import numpy as np
import os

In [4]:
#get the median income and ami csv file
df = pd.read_csv("Median_Income_and_AMI.csv")
df

,tract,med_hh_income,med_hh_income_universe,ami_category,below_med_income,below_60pct_med_income,below_moderate_income,sup_dist,csa,spa,ESRI_OID,Shape__Area,Shape__Length
0,6037199700,38892.0,1204,Very Low Income,Yes,Yes,Yes,District 1,Los Angeles - Wholesale District,SPA 4 - Metro,2347,1.041050e+07,13808.463240
1,6037199801,41027.0,903,Very Low Income,Yes,Yes,Yes,District 1,Los Angeles - Lincoln Heights,SPA 4 - Metro,2348,3.724107e+06,9459.391827
2,6037199802,42500.0,612,Very Low Income,Yes,Yes,Yes,District 1,Los Angeles - Lincoln Heights,SPA 4 - Metro,2349,3.296129e+06,8868.744225
3,6037199900,37232.0,845,Very Low Income,Yes,Yes,Yes,District 1,Los Angeles - Lincoln Heights,SPA 4 - Metro,2350,4.782361e+06,10141.728020
4,6037201110,65000.0,782,Low Income,Yes,No,Yes,District 1,Los Angeles - El Sereno,SPA 4 - Metro,2351,1.099246e+07,15893.383640
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2490,6037554516,126450.0,1215,Above Moderate Income,No,No,No,District 4,City of Cerritos,SPA 7 - East,4837,1.555650e+07,21274.227410
2491,6037554517,107672.0,1352,Above Moderate Income,No,No,No,District 4,City of Cerritos,SPA 7 - East,4838,1.421767e+07,15905.089170
2492,6037554518,104439.0,1558,Above Moderate Income,No,No,No,District 4,City of Cerritos,SPA 7 - East,4839,1.938903e+07,21218.412990
2493,6037554519,131012.0,1216,Above Moderate Income,No,No,No,District 4,City of Cerritos,SPA 7 - East,4840,1.866694e+07,19500.866810
2494,6037554521,90280.0,1863,Low Income,No,No,Yes,District 4,City of Cerritos,SPA 7 - East,4841,5.352220e+07,37625.839750

In [12]:
#get the parking citations csv file
df2 = pd.read_csv("Parking_Citations.csv")
df2

C:\Users\mail2\AppData\Local\Temp\ipykernel_5856\3656394924.py:1: DtypeWarning: Columns (0,7,19,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv("Parking_Citations.csv")

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,Plate Expiry Date,VIN,Make,Body Style,...,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude,Agency Description,Color Description,Body Style Description
0,1103341116,12/21/2015,1251.0,NaN,NaN,CA,200304.0,NaN,HOND,PA,...,01521,1.0,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04,NaN,NaN,NaN
1,1103700150,12/21/2015,1435.0,NaN,NaN,CA,201512.0,NaN,GMC,VN,...,1C51,1.0,4000A1,NO EVIDENCE OF REG,50.0,9.999900e+04,9.999900e+04,NaN,NaN,NaN
2,1104803000,12/21/2015,2055.0,NaN,NaN,CA,201503.0,NaN,NISS,PA,...,2R2,2.0,8939,WHITE CURB,58.0,6.439998e+06,1.802686e+06,NaN,NaN,NaN
3,1104820732,12/26/2015,1515.0,NaN,NaN,CA,NaN,NaN,ACUR,PA,...,2F11,2.0,000,17104h,NaN,6.440041e+06,1.802686e+06,NaN,NaN,NaN
4,1105461453,09/15/2015,115.0,NaN,NaN,CA,200316.0,NaN,CHEV,PA,...,1FB70,1.0,8069A,NO STOPPING/STANDING,93.0,9.999900e+04,9.999900e+04,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15591342,4549303301,05/26/2022,1639.0,VL18,0.0,CA,202211.0,NaN,VOLK,PA,...,NaN,51.0,88.13B+,METER EXP.,63.0,6.419829e+06,1.819688e+06,51 - DOT - WESTERN,BLACK,PASSENGER CAR
15591343,4549469072,05/26/2022,1705.0,NaN,0.0,CA,0.0,NaN,MERZ,PA,...,0403B,54.0,80.70,NO STOPPING/ANTI-GRIDLOCK ZONE,163.0,6.456859e+06,1.858219e+06,54 - DOT - HOLLYWOOD,WHITE,PASSENGER CAR
15591344,4549851596,05/26/2022,1641.0,NaN,0.0,CA,202208.0,NaN,HOND,PA,...,0058B,53.0,80.69A+,STOP/STAND PROHIBIT,93.0,6.474061e+06,1.727435e+06,53 - DOT - VALLEY,BLACK,PASSENGER CAR
15591345,4547815705,05/26/2022,1639.0,MM99B,0.0,CA,202302.0,NaN,TOYT,PA,...,0103R,51.0,88.13B+,METER EXP.,63.0,6.455838e+06,1.845230e+06,51 - DOT - WESTERN,BLACK,PASSENGER CAR
15591346,4549623260,05/26/2022,1647.0,NaN,0.0,CA,202208.0,NaN,FORD,PA,...,NaN,55.0,80.56E4+,RED ZONE,93.0,6.473777e+06,1.825187e+06,55 - DOT - SOUTHERN,WHITE,PASSENGER CAR

### Median Income and AMI

Median income and AMI will have statistics for median household income, AMI category based on median household income, and comparing median household income to AMI cateories

In [6]:

df.head()

,tract,med_hh_income,med_hh_income_universe,ami_category,below_med_income,below_60pct_med_income,below_moderate_income,sup_dist,csa,spa,ESRI_OID,Shape__Area,Shape__Length
0,6037199700,38892.0,1204,Very Low Income,Yes,Yes,Yes,District 1,Los Angeles - Wholesale District,SPA 4 - Metro,2347,1.041050e+07,13808.463240
1,6037199801,41027.0,903,Very Low Income,Yes,Yes,Yes,District 1,Los Angeles - Lincoln Heights,SPA 4 - Metro,2348,3.724107e+06,9459.391827
2,6037199802,42500.0,612,Very Low Income,Yes,Yes,Yes,District 1,Los Angeles - Lincoln Heights,SPA 4 - Metro,2349,3.296129e+06,8868.744225
3,6037199900,37232.0,845,Very Low Income,Yes,Yes,Yes,District 1,Los Angeles - Lincoln Heights,SPA 4 - Metro,2350,4.782361e+06,10141.728020
4,6037201110,65000.0,782,Low Income,Yes,No,Yes,District 1,Los Angeles - El Sereno,SPA 4 - Metro,2351,1.099246e+07,15893.383640

In [7]:
df.shape

(2495, 13)

In [8]:
df.describe()

,tract,med_hh_income,med_hh_income_universe,ESRI_OID,Shape__Area,Shape__Length
count,2.495000e+03,2458.000000,2495.000000,2495.000000,2.495000e+03,2495.000000
mean,6.037403e+09,76849.334418,1335.672946,3594.000000,4.579716e+07,20273.817017
std,2.303896e+05,35546.132788,533.910989,720.388784,4.270580e+08,34074.651233
min,6.037101e+09,4918.000000,0.000000,2347.000000,4.836532e+05,2815.257443
25%,6.037209e+09,51157.500000,988.000000,2970.500000,5.921008e+06,10607.040730
50%,6.037403e+09,69698.000000,1282.000000,3594.000000,1.025761e+07,14365.057030
75%,6.037552e+09,94515.500000,1625.000000,4217.500000,1.835792e+07,19904.426710
max,6.037980e+09,250001.000000,5617.000000,4841.000000,1.608691e+10,915242.577100

In [9]:
df.columns

Index(['tract', 'med_hh_income', 'med_hh_income_universe', 'ami_category',
       'below_med_income', 'below_60pct_med_income', 'below_moderate_income',
       'sup_dist', 'csa', 'spa', 'ESRI_OID', 'Shape__Area', 'Shape__Length'],
      dtype='object')

In [13]:
df2.columns

Index(['Ticket number', 'Issue Date', 'Issue time', 'Meter Id', 'Marked Time',
       'RP State Plate', 'Plate Expiry Date', 'VIN', 'Make', 'Body Style',
       'Color', 'Location', 'Route', 'Agency', 'Violation code',
       'Violation Description', 'Fine amount', 'Latitude', 'Longitude',
       'Agency Description', 'Color Description', 'Body Style Description'],
      dtype='object')

In [16]:
#finding types of each column
df.dtypes

tract                       int64
med_hh_income             float64
med_hh_income_universe      int64
ami_category               object
below_med_income           object
below_60pct_med_income     object
below_moderate_income      object
sup_dist                   object
csa                        object
spa                        object
ESRI_OID                    int64
Shape__Area               float64
Shape__Length             float64
dtype: object

In [25]:
df.index

RangeIndex(start=0, stop=2495, step=1)

In [17]:
df['csa'].unique(), df2['Location']

(array(['Los Angeles - Wholesale District',
        'Los Angeles - Lincoln Heights', 'Los Angeles - El Sereno',
        'Los Angeles - Highland Park', 'Los Angeles - University Hills',
        'Los Angeles - Boyle Heights', 'City of Pomona',
        'City of Diamond Bar', 'Unincorporated - Rowland Heights',
        'City of Industry', 'City of Walnut', 'Unincorporated - Covina',
        'City of Covina', 'City of San Dimas',
        'Unincorporated - Covina (Charter Oak)', 'City of Glendora',
        'Unincorporated - Azusa', 'City of Azusa', 'City of Norwalk',
        'City of Artesia', 'City of Lakewood', 'City of Hawaiian Gardens',
        'City of Long Beach', 'City of Cerritos',
        'Los Angeles - Little Tokyo', 'Los Angeles - Chinatown',
        'Los Angeles - Downtown', 'Los Angeles - Temple-Beaudry',
        'Los Angeles - Historic Filipinotown', 'Los Angeles - Westlake',
        'City of Irwindale', 'City of Baldwin Park', 'City of West Covina',
        'City of Signal Hill', 'Los Angeles - Pico-Union',
        'Los Angeles - Hancock Park', 'Los Angeles - Wilshire Center',
        'Los Angeles - Little Bangladesh', 'Los Angeles - Koreatown',
        'Unincorporated - Bassett', 'City of La Puente',
        'Unincorporated - West Puente Valley', 'Unincorporated - Valinda',
        'Unincorporated - San Jose Hills',
        'Unincorporated - Avocado Heights',
        'Unincorporated - North Whittier',
        'Unincorporated - Hacienda Heights', 'Los Angeles - Tujunga',
        'Los Angeles - Sun Valley', 'Los Angeles - Sunland',
        'Los Angeles - Lakeview Terrace', 'Los Angeles - Shadow Hills',
        'Los Angeles - Pacoima', 'Los Angeles - Country Club Park',
        'Los Angeles - Melrose', 'Los Angeles - Park La Brea',
        'Los Angeles - Carthay', 'Los Angeles - Miracle Mile',
        'Los Angeles - South Carthay', 'Los Angeles - Crestview',
        'Los Angeles - Mid-city', 'City of La Verne', 'City of Duarte',
        'City of Bradbury', 'City of Monrovia', 'City of Arcadia',
        'City of Sierra Madre', 'City of Downey', 'City of Avalon',
        'Unincorporated - Santa Catalina Island',
        'Unincorporated - Athens-Westmont', 'City of Inglewood',
        'Unincorporated - Lennox', 'Unincorporated - Kagel/Lopez Canyons',
        'Los Angeles - Sylmar', 'Los Angeles - Granada Hills',
        'Los Angeles - Victoria Park', 'Los Angeles - St Elmo Village',
        'Los Angeles - Lafayette Square',
        'Los Angeles - Cloverdale/Cochran', 'Los Angeles - Longwood',
        'Los Angeles - Wellington Square', 'Los Angeles - West Adams',
        'Los Angeles - Jefferson Park', 'Los Angeles - Crenshaw District',
        'Los Angeles - Exposition', 'Los Angeles - Alsace',
        'Los Angeles - Baldwin Hills', 'Los Angeles - Harvard Heights',
        'Los Angeles - University Park', 'Unincorporated - Duarte',
        'Unincorporated - Monrovia', 'Unincorporated - Arcadia',
        'City of Temple City', 'City of Rosemead', 'City of El Monte',
        'City of South El Monte', 'City of Hawthorne',
        'Unincorporated - Del Aire', 'Unincorporated - Wiseburn',
        'Unincorporated - Hawthorne', 'City of Gardena',
        'Los Angeles - Porter Ranch', 'Los Angeles - Mission Hills',
        'Los Angeles - North Hills', 'Los Angeles - Northridge',
        'Los Angeles - Chatsworth', 'Unincorporated - West Chatsworth',
        'Los Angeles - West Hills', 'Los Angeles - Canoga Park',
        'Unincorporated - Lake Manor', 'Los Angeles - Exposition Park',
        'Los Angeles - Adams-Normandie', 'Los Angeles - Central',
        'City of Manhattan Beach', 'Los Angeles - Vernon Central',
        'Los Angeles - South Park', 'Unincorporated - East Pasadena',
        'City of Pasadena', 'Unincorporated - Altadena',
        'City of La Canada Flintridge',
        'Unincorporated - El Camino Village', 'City of Lawndale',
        'Unincorporated - La Rambla', 'City of El Segundo',
        'City of Redondo Beach', 'City of Hermosa Beach',
        'Los Angeles - Winnetka', 'Los Angeles - Arleta',
        'Los Angeles - Panorama City', 'Los Angeles - West Vernon',
        'Los Angeles - Vermont Square', 'Los Angeles - Leimert Park',
        'Los Angeles - Hyde Park', 'Los Angeles - View Heights',
        'Unincorporated - San Pasqual', 'City of San Marino',
        'Unincorporated - Northeast San Gabriel', 'City of San Gabriel',
        'City of Alhambra', 'City of South Pasadena', 'City of Torrance',
        'City of Lomita', 'City of Rolling Hills Estates',
        'City of Palos Verdes Estates', 'Los Angeles - North Hollywood',
        'Los Angeles - Harvard Park', 'Los Angeles - Vermont Knolls',
        'Los Angeles - Manchester Square', 'Los Angeles - Gramercy Place',
        'Los Angeles - Vermont Vista', 'Los Angeles - Florence-Firestone',
        'Los Angeles - Green Meadows', 'City of Monterey Park',
        'Unincorporated - South San Gabriel', 'City of Montebello',
        'City of La Habra Heights', 'City of Whittier',
        'Unincorporated - Whittier', 'City of Rancho Palos Verdes',
        'City of Rolling Hills', 'City of West Hollywood',
        'City of Beverly Hills', 'City of Santa Monica',
        'Los Angeles - Valley Glen', 'Los Angeles - Van Nuys',
        'Los Angeles - Valley Village', 'Los Angeles - Sherman Oaks',
        'Los Angeles - Toluca Lake', 'Los Angeles - Toluca Woods',
        'Los Angeles - Century Palms/Cove',
        'Los Angeles - Figueroa Park Square', 'Los Angeles - Watts',
        'Los Angeles - Beverly Crest', 'Los Angeles - Bel Air',
        'Los Angeles - Brentwood', 'Los Angeles - Mandeville Canyon',
        'Los Angeles - Pacific Palisades',
        'Los Angeles - Palisades Highlands', 'City of Pico Rivera',
        'Unincorporated - West Whittier/Los Nietos',
        'Unincorporated - South Whittier', 'City of Santa Fe Springs',
        'City of Culver City', 'Unincorporated - Marina del Rey',
        'Unincorporated - Ladera Heights',
        'Unincorporated - View Park/Windsor Hills', 'City of Calabasas',
        'Unincorporated - Santa Monica Mountains', 'City of Agoura Hills',
        'City of Westlake Village', 'Unincorporated - Elizabeth Lake',
        'City of Malibu', 'City of Palmdale', 'Unincorporated - Hi Vista',
        'Unincorporated - Lake Los Angeles', 'City of Lancaster',
        'Los Angeles - Lake Balboa', 'Los Angeles - Reseda',
        'Los Angeles - Reseda Ranch', 'Los Angeles - Westwood',
        'Los Angeles - Century City', 'Los Angeles - West Los Angeles',
        'Los Angeles - Rancho Park', 'Los Angeles - Cheviot Hills',
        'Los Angeles - Beverlywood', 'City of La Mirada',
        'Unincorporated - East Whittier',
        'Unincorporated - East La Mirada',
        'Unincorporated - East Los Angeles',
        'Unincorporated - North Lancaster', 'Unincorporated - Quartz Hill',
        'Unincorporated - West Antelope Valley',
        'Unincorporated - Leona Valley', 'Los Angeles - Woodland Hills',
        'Los Angeles - Cadillac-Corning', 'Los Angeles - Reynier Village',
        'Los Angeles - Palms', 'Los Angeles - Regent Square',
        'Los Angeles - Faircrest Heights', 'Los Angeles - Mar Vista',
        'Los Angeles - Venice', 'City of Commerce',
        'City of Huntington Park', 'Unincorporated - Florence-Firestone',
        'Los Angeles - Westchester', 'City of Maywood',
        'Unincorporated - Roosevelt',
        'Unincorporated - Littlerock/Pearblossom',
        'Unincorporated - White Fence Farms', 'Unincorporated - Anaverde',
        'Los Angeles - Harbor City',
        'Unincorporated - Southeast Antelope Valley',
        'Unincorporated - Acton', 'City of Santa Clarita',
        'Unincorporated - Agua Dulce', 'Los Angeles - Encino',
        'Los Angeles - Tarzana', 'Los Angeles - Marina Peninsula',
        'Los Angeles - Del Rey', 'Los Angeles - Playa Vista',
        'Los Angeles - Playa Del Rey', 'Los Angeles - Harbor Gateway',
        'City of Bell', 'City of Bell Gardens', 'City of Cudahy',
        'Unincorporated - Walnut Park', 'City of South Gate',
        'Unincorporated - Angeles National Forest',
        'Unincorporated - Llano', 'Unincorporated - Palmdale',
        'Unincorporated - Saugus/Canyon Country',
        'Unincorporated - San Francisquito Canyon/Bouquet Canyon',
        'Unincorporated - Castaic', 'Unincorporated - Val Verde',
        'Los Angeles - Studio City', 'Los Angeles - Hollywood Hills',
        'Los Angeles - Eagle Rock', 'Los Angeles - Harbor Pines',
        'Los Angeles - Wilmington', 'Los Angeles - San Pedro',
        'Unincorporated - La Crescenta-Montrose', 'City of Lynwood',
        'Unincorporated - Willowbrook', 'Unincorporated - Athens Village',
        'City of Carson',
        'Unincorporated - Rosewood/West Rancho Dominguez',
        'City of Compton', 'Unincorporated - Twin Lakes/Oat Mountain',
        'Unincorporated - Stevenson Ranch', 'City of Burbank',
        'Unincorporated - South Edwards', 'Los Angeles - Los Feliz',
        'Los Angeles - Elysian Park', 'City of Vernon',
        'Unincorporated - West LA', 'Los Angeles - Mt. Washington',
        'Los Angeles - Elysian Valley', 'Los Angeles - Glassell Park',
        'Los Angeles - Atwater Village', 'Los Angeles - Silverlake',
        'Los Angeles - Hollywood', 'City of Glendale',
        'Unincorporated - East Rancho Dominguez',
        'Unincorporated - Rancho Dominguez',
        'Unincorporated - West Carson',
        'Los Angeles - Angeles National Forest',
        'Unincorporated - Whittier Narrows',
        'Unincorporated - Universal City', 'Los Angeles - Thai Town',
        'Los Angeles - Little Armenia', 'Los Angeles - East Hollywood',
        'City of San Fernando', 'City of Claremont',
        'Los Angeles - Echo Park', 'Los Angeles - Angelino Heights',
        'Unincorporated - Pomona', 'City of Bellflower',
        'City of Paramount'], dtype=object),
 0              13147 WELBY WAY
 1                525 S MAIN ST
 2                200 WORLD WAY
 3                100 WORLD WAY
 4           GEORGIA ST/OLYMPIC
                    ...
 15591342     1301 ELECTRIC AVE
 15591343    7165 SUNSET BLVD W
 15591344            510 6TH ST
 15591345     700 BURNSIDE AV N
 15591346        4200 MENLO AVE
 Name: Location, Length: 15591347, dtype: object)

In [20]:
#function to single out the city/community from the string
def a (city):
    if ' - ' in city:
        idx = city.index('- ')
    else:
        idx = -2
    return city[idx+2:]
df['csa'] = df['csa'].apply(a)

In [21]:
df

,tract,med_hh_income,med_hh_income_universe,ami_category,below_med_income,below_60pct_med_income,below_moderate_income,sup_dist,csa,spa,ESRI_OID,Shape__Area,Shape__Length
0,6037199700,38892.0,1204,Very Low Income,Yes,Yes,Yes,District 1,Wholesale District,SPA 4 - Metro,2347,1.041050e+07,13808.463240
1,6037199801,41027.0,903,Very Low Income,Yes,Yes,Yes,District 1,Lincoln Heights,SPA 4 - Metro,2348,3.724107e+06,9459.391827
2,6037199802,42500.0,612,Very Low Income,Yes,Yes,Yes,District 1,Lincoln Heights,SPA 4 - Metro,2349,3.296129e+06,8868.744225
3,6037199900,37232.0,845,Very Low Income,Yes,Yes,Yes,District 1,Lincoln Heights,SPA 4 - Metro,2350,4.782361e+06,10141.728020
4,6037201110,65000.0,782,Low Income,Yes,No,Yes,District 1,El Sereno,SPA 4 - Metro,2351,1.099246e+07,15893.383640
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2490,6037554516,126450.0,1215,Above Moderate Income,No,No,No,District 4,City of Cerritos,SPA 7 - East,4837,1.555650e+07,21274.227410
2491,6037554517,107672.0,1352,Above Moderate Income,No,No,No,District 4,City of Cerritos,SPA 7 - East,4838,1.421767e+07,15905.089170
2492,6037554518,104439.0,1558,Above Moderate Income,No,No,No,District 4,City of Cerritos,SPA 7 - East,4839,1.938903e+07,21218.412990
2493,6037554519,131012.0,1216,Above Moderate Income,No,No,No,District 4,City of Cerritos,SPA 7 - East,4840,1.866694e+07,19500.866810
2494,6037554521,90280.0,1863,Low Income,No,No,Yes,District 4,City of Cerritos,SPA 7 - East,4841,5.352220e+07,37625.839750

In [34]:
#checking if csa column has nans
df['csa'].hasnans

False

In [36]:
#checking if ami category colunn has nans
df['ami_category'].hasnans

True

In [37]:
#checking if median_hh_income has nans
df['med_hh_income'].hasnans

True

In [42]:
#finding all the rows in the dataframe where med_hh_income column ins NaN
df.loc[ df['med_hh_income'].isna() ]

,tract,med_hh_income,med_hh_income_universe,ami_category,below_med_income,below_60pct_med_income,below_moderate_income,sup_dist,csa,spa,ESRI_OID,Shape__Area,Shape__Length
446,6037216301,NaN,614,NaN,NaN,NaN,NaN,District 2,Miracle Mile,SPA 4 - Metro,2793,6.049547e+06,11309.816320
502,6037578100,NaN,0,NaN,NaN,NaN,NaN,District 4,City of Long Beach,SPA 8 - South Bay,2849,1.851637e+07,18912.709490
504,6037599100,NaN,79,NaN,NaN,NaN,NaN,District 4,Santa Catalina Island,SPA 8 - South Bay,2851,3.698756e+09,554591.259900
761,6037222700,NaN,108,NaN,NaN,NaN,NaN,District 2,Exposition Park,SPA 6 - South,3108,9.012062e+06,13506.623730
896,6037115103,NaN,11,NaN,NaN,NaN,NaN,District 3,Northridge,SPA 2 - San Fernando,3243,1.632932e+07,22141.574990
1458,6037265301,NaN,0,NaN,NaN,NaN,NaN,District 3,Westwood,SPA 5 - West,3805,1.737124e+07,20071.778700
1560,6037901003,NaN,0,NaN,NaN,NaN,NaN,District 5,City of Lancaster,SPA 1 - Antelope Valley,3907,2.809203e+07,21201.257350
1658,6037273403,NaN,1020,NaN,NaN,NaN,NaN,District 3,Venice,SPA 5 - West,4005,2.869621e+06,8586.103161
2052,6037920200,NaN,0,NaN,NaN,NaN,NaN,District 5,Castaic,SPA 2 - San Fernando,4399,1.222087e+08,64176.721580
2072,6037980001,NaN,0,NaN,NaN,NaN,NaN,District 5,City of Burbank,SPA 2 - San Fernando,4419,2.508105e+07,22534.656490
2073,6037980002,NaN,0,NaN,NaN,NaN,NaN,District 2,City of Carson,SPA 8 - South Bay,4420,7.507961e+07,37687.147690
2074,6037980003,NaN,0,NaN,NaN,NaN,NaN,District 5,South Edwards,SPA 1 - Antelope Valley,4421,2.082305e+09,272360.490500
2075,6037980004,NaN,0,NaN,NaN,NaN,NaN,District 5,City of Palmdale,SPA 1 - Antelope Valley,4422,3.858493e+08,88089.895700
2076,6037980005,NaN,0,NaN,NaN,NaN,NaN,District 4,City of Torrance,SPA 8 - South Bay,4423,4.363157e+07,31657.990880
2077,6037980006,NaN,0,NaN,NaN,NaN,NaN,District 4,City of Long Beach,SPA 8 - South Bay,4424,3.620442e+07,38004.976260
2078,6037980007,NaN,0,NaN,NaN,NaN,NaN,District 4,City of Long Beach,SPA 8 - South Bay,4425,2.909938e+07,24048.956280
2079,6037980008,NaN,17,NaN,NaN,NaN,NaN,District 3,Van Nuys,SPA 2 - San Fernando,4426,3.652047e+07,33527.736660
2080,6037980009,NaN,0,NaN,NaN,NaN,NaN,District 5,Los Feliz,SPA 4 - Metro,4427,2.284265e+08,78138.601740
2083,6037980012,NaN,0,NaN,NaN,NaN,NaN,District 4,City of Downey,SPA 7 - East,4430,9.903054e+06,15069.521690
2084,6037980013,NaN,0,NaN,NaN,NaN,NaN,District 2,City of El Segundo,SPA 8 - South Bay,4431,5.705245e+07,33824.623980
2085,6037980014,NaN,11,NaN,NaN,NaN,NaN,District 4,Wilmington,SPA 8 - South Bay,4432,8.046195e+07,67612.005400
2089,6037980018,NaN,0,NaN,NaN,NaN,NaN,District 4,City of Long Beach,SPA 8 - South Bay,4436,7.969295e+07,54854.595410
2091,6037980020,NaN,0,NaN,NaN,NaN,NaN,District 5,Sun Valley,SPA 2 - San Fernando,4438,9.178436e+07,60339.110550
2092,6037980021,NaN,14,NaN,NaN,NaN,NaN,District 5,Lakeview Terrace,SPA 2 - San Fernando,4439,7.508840e+07,50381.103470
2093,6037980022,NaN,0,NaN,NaN,NaN,NaN,District 3,Granada Hills,SPA 2 - San Fernando,4440,6.940722e+07,41500.667960
2223,6037980023,NaN,0,NaN,NaN,NaN,NaN,District 3,West Hills,SPA 2 - San Fernando,4570,5.692099e+07,39154.636780
2225,6037980026,NaN,0,NaN,NaN,NaN,NaN,District 5,Angeles National Forest,SPA 2 - San Fernando,4572,1.496110e+08,101888.807200
2226,6037980028,NaN,0,NaN,NaN,NaN,NaN,District 2,Westchester,SPA 5 - West,4573,1.818711e+08,80476.270920
2227,6037980030,NaN,0,NaN,NaN,NaN,NaN,District 2,City of El Segundo,SPA 8 - South Bay,4574,4.475804e+07,28958.117330
2228,6037980031,NaN,22,NaN,NaN,NaN,NaN,District 4,San Pedro,SPA 8 - South Bay,4575,2.784858e+08,79769.849940
2229,6037980033,NaN,14,NaN,NaN,NaN,NaN,District 4,City of Long Beach,SPA 8 - South Bay,4576,3.061391e+08,76112.964180
2230,6037980034,NaN,9,NaN,NaN,NaN,NaN,District 4,City of Santa Fe Springs,SPA 7 - East,4577,6.957459e+07,60488.936120
2232,6037980036,NaN,164,NaN,NaN,NaN,NaN,District 1,Whittier Narrows,SPA 3 - San Gabriel,4579,9.410894e+07,63183.082620
2233,6037980037,NaN,0,NaN,NaN,NaN,NaN,District 2,City of Carson,SPA 8 - South Bay,4580,1.376446e+07,14866.138290
2234,6037980038,NaN,0,NaN,NaN,NaN,NaN,District 2,Ladera Heights,SPA 5 - West,4581,4.852656e+07,42566.840170
2235,6037980039,NaN,0,NaN,NaN,NaN,NaN,District 5,Universal City,SPA 2 - San Fernando,4582,1.464017e+07,17601.678330
2442,6037402404,NaN,4,NaN,NaN,NaN,NaN,District 1,Pomona,SPA 3 - San Gabriel,4789,4.419568e+07,35663.185880

In [47]:
#all of the rows having NaN in med_hh_income column have NaNs in ami_catgory, below_med_income, below_60pct_med_income, and below_moderate_income as well
df.loc[ df['med_hh_income'].isna()].shape
df.shape

(2495, 13)

In [48]:
#shape of df once dropping rows with NaN
df.dropna().shape

(2458, 13)

In [98]:
#dropping rows with nans
df.dropna(inplace = True)

(2458, 13)

In [102]:
df['med_hh_income'].hasnans

False

In [103]:
df['ami_category'].hasnans

False

In [65]:
i = 0
cols = df.columns
cols

Index(['tract', 'med_hh_income', 'med_hh_income_universe', 'ami_category',
       'below_med_income', 'below_60pct_med_income', 'below_moderate_income',
       'sup_dist', 'csa', 'spa', 'ESRI_OID', 'Shape__Area', 'Shape__Length'],
      dtype='object')

In [82]:
print(i,cols[i])
print(pd.Series(df[cols[i]].unique()).sort_values())
i=i+1

IndexError: index 13 is out of bounds for axis 0 with size 13

In [69]:
l=[1,3,2]
pd.Series(l).sort_values()

0    1
2    2
1    3
dtype: int64

In [93]:
#drop a the 'City of' part of the string as that is unnecessary
fncof = lambda x : x if 'City of ' not in x else x[8:]
df['csa'] = df['csa'].apply(fncof)

In [94]:
#checking the unique values
df['csa'].unique()

array(['Wholesale District', 'Lincoln Heights', 'El Sereno',
       'Highland Park', 'University Hills', 'Boyle Heights', 'Pomona',
       'Diamond Bar', 'Rowland Heights', 'Industry', 'Walnut', 'Covina',
       'San Dimas', 'Covina (Charter Oak)', 'Glendora', 'Azusa',
       'Norwalk', 'Artesia', 'Lakewood', 'Hawaiian Gardens', 'Long Beach',
       'Cerritos', 'Little Tokyo', 'Chinatown', 'Downtown',
       'Temple-Beaudry', 'Historic Filipinotown', 'Westlake', 'Irwindale',
       'Baldwin Park', 'West Covina', 'Signal Hill', 'Pico-Union',
       'Hancock Park', 'Wilshire Center', 'Little Bangladesh',
       'Koreatown', 'Bassett', 'La Puente', 'West Puente Valley',
       'Valinda', 'San Jose Hills', 'Avocado Heights', 'North Whittier',
       'Hacienda Heights', 'Tujunga', 'Sun Valley', 'Sunland',
       'Lakeview Terrace', 'Shadow Hills', 'Pacoima', 'Country Club Park',
       'Melrose', 'Park La Brea', 'Carthay', 'Miracle Mile',
       'South Carthay', 'Crestview', 'Mid-city', 'La Verne', 'Duarte',
       'Bradbury', 'Monrovia', 'Arcadia', 'Sierra Madre', 'Downey',
       'Avalon', 'Santa Catalina Island', 'Athens-Westmont', 'Inglewood',
       'Lennox', 'Kagel/Lopez Canyons', 'Sylmar', 'Granada Hills',
       'Victoria Park', 'St Elmo Village', 'Lafayette Square',
       'Cloverdale/Cochran', 'Longwood', 'Wellington Square',
       'West Adams', 'Jefferson Park', 'Crenshaw District', 'Exposition',
       'Alsace', 'Baldwin Hills', 'Harvard Heights', 'University Park',
       'Temple City', 'Rosemead', 'El Monte', 'South El Monte',
       'Hawthorne', 'Del Aire', 'Wiseburn', 'Gardena', 'Porter Ranch',
       'Mission Hills', 'North Hills', 'Northridge', 'Chatsworth',
       'West Chatsworth', 'West Hills', 'Canoga Park', 'Lake Manor',
       'Exposition Park', 'Adams-Normandie', 'Central', 'Manhattan Beach',
       'Vernon Central', 'South Park', 'East Pasadena', 'Pasadena',
       'Altadena', 'La Canada Flintridge', 'El Camino Village',
       'Lawndale', 'La Rambla', 'El Segundo', 'Redondo Beach',
       'Hermosa Beach', 'Winnetka', 'Arleta', 'Panorama City',
       'West Vernon', 'Vermont Square', 'Leimert Park', 'Hyde Park',
       'View Heights', 'San Pasqual', 'San Marino',
       'Northeast San Gabriel', 'San Gabriel', 'Alhambra',
       'South Pasadena', 'Torrance', 'Lomita', 'Rolling Hills Estates',
       'Palos Verdes Estates', 'North Hollywood', 'Harvard Park',
       'Vermont Knolls', 'Manchester Square', 'Gramercy Place',
       'Vermont Vista', 'Florence-Firestone', 'Green Meadows',
       'Monterey Park', 'South San Gabriel', 'Montebello',
       'La Habra Heights', 'Whittier', 'Rancho Palos Verdes',
       'Rolling Hills', 'West Hollywood', 'Beverly Hills', 'Santa Monica',
       'Valley Glen', 'Van Nuys', 'Valley Village', 'Sherman Oaks',
       'Toluca Lake', 'Toluca Woods', 'Century Palms/Cove',
       'Figueroa Park Square', 'Watts', 'Beverly Crest', 'Bel Air',
       'Brentwood', 'Mandeville Canyon', 'Pacific Palisades',
       'Palisades Highlands', 'Pico Rivera', 'West Whittier/Los Nietos',
       'South Whittier', 'Santa Fe Springs', 'Culver City',
       'Marina del Rey', 'Ladera Heights', 'View Park/Windsor Hills',
       'Calabasas', 'Santa Monica Mountains', 'Agoura Hills',
       'Westlake Village', 'Elizabeth Lake', 'Malibu', 'Palmdale',
       'Hi Vista', 'Lake Los Angeles', 'Lancaster', 'Lake Balboa',
       'Reseda', 'Reseda Ranch', 'Westwood', 'Century City',
       'West Los Angeles', 'Rancho Park', 'Cheviot Hills', 'Beverlywood',
       'La Mirada', 'East Whittier', 'East La Mirada', 'East Los Angeles',
       'North Lancaster', 'Quartz Hill', 'West Antelope Valley',
       'Leona Valley', 'Woodland Hills', 'Cadillac-Corning',
       'Reynier Village', 'Palms', 'Regent Square', 'Faircrest Heights',
       'Mar Vista', 'Venice', 'Commerce', 'Huntington Park',
       'Westchester', 'Maywood', 'Roosevelt', 'Littlerock/Pearblossom',
       'White Fence Farms', 'Anaverde', 'Harbor City',
       'Southeast Antelope Valley', 'Acton', 'Santa Clarita',
       'Agua Dulce', 'Encino', 'Tarzana', 'Marina Peninsula', 'Del Rey',
       'Playa Vista', 'Playa Del Rey', 'Harbor Gateway', 'Bell',
       'Bell Gardens', 'Cudahy', 'Walnut Park', 'South Gate',
       'Angeles National Forest', 'Llano', 'Saugus/Canyon Country',
       'San Francisquito Canyon/Bouquet Canyon', 'Castaic', 'Val Verde',
       'Studio City', 'Hollywood Hills', 'Eagle Rock', 'Harbor Pines',
       'Wilmington', 'San Pedro', 'La Crescenta-Montrose', 'Lynwood',
       'Willowbrook', 'Athens Village', 'Carson',
       'Rosewood/West Rancho Dominguez', 'Compton',
       'Twin Lakes/Oat Mountain', 'Stevenson Ranch', 'Burbank',
       'South Edwards', 'Los Feliz', 'Elysian Park', 'Vernon', 'West LA',
       'Mt. Washington', 'Elysian Valley', 'Glassell Park',
       'Atwater Village', 'Silverlake', 'Hollywood', 'Glendale',
       'East Rancho Dominguez', 'Rancho Dominguez', 'West Carson',
       'Whittier Narrows', 'Universal City', 'Thai Town',
       'Little Armenia', 'East Hollywood', 'San Fernando', 'Claremont',
       'Echo Park', 'Angelino Heights', 'Bellflower', 'Paramount'],
      dtype=object)